/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  sepolia: {
    vault_factory: {
      address:
        "0x7f842398b9c105fa609a80957195a011aff4e7506a8475cb66e555bf4c7c9a8",
      abi: [
        {
          type: "impl",
          name: "FactoryExternal",
          interface_name: "starkwill::vault_factory::IVaultFactory",
        },
        {
          type: "interface",
          name: "starkwill::vault_factory::IVaultFactory",
          items: [
            {
              type: "function",
              name: "create_vault",
              inputs: [
                {
                  name: "checkin_period_secs",
                  type: "core::integer::u64",
                },
                {
                  name: "grace_period_secs",
                  type: "core::integer::u64",
                },
                {
                  name: "cancelable_until_ts",
                  type: "core::integer::u64",
                },
                {
                  name: "guardian_1",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "guardian_2",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "guardian_3",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_vault_for_owner",
              inputs: [
                {
                  name: "owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "vault_class_hash",
              type: "core::starknet::class_hash::ClassHash",
            },
          ],
        },
        {
          type: "event",
          name: "starkwill::vault_factory::vault_factory::VaultCreated",
          kind: "struct",
          members: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "vault_address",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "vault_index",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "starkwill::vault_factory::vault_factory::Event",
          kind: "enum",
          variants: [
            {
              name: "VaultCreated",
              type: "starkwill::vault_factory::vault_factory::VaultCreated",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x36d359897e2fd87270ac99fc8f910c60f4a3ce509f33901cf5ed56e3769a9a3",
    },
  },
} as const;

export default deployedContracts;
